### ISSUE TITLE
Babel 7.0.0 integration

### ISSUE THREAD

**Issue by chefkoch333** [quasarframework/quasar-cli#179]
### Software version

OS: macos 10.13.6
Node: v10.10.0
NPM: 6.4.1
Any other software related to your bug:

### What did you get as the error?
Babel has removed core-js from the runtime package  https://github.com/babel/babel/releases/tag/v7.0.0-beta.56

quasar build results in an error using babel 7.0.0-beta.56 or above:
(node:6214) UnhandledPromiseRejectionWarning:   Error: Cannot find module '@babel/runtime/core-js/get-iterator'

### What were you expecting?
QuasarCli should work with the latest babel 7.0.0 release.

### What steps did you take, to get the error?
quasar build using babel 7.0.0

**Comment by adamkpurdy** [comment]
I was experiencing this same problem.

I followed along here: http://babeljs.io/docs/en/next/babel-plugin-transform-runtime

Basically I removed the old babel runtime in my package.json : `"@babel/runtime": "^7.0.0-beta.56"`, and replaced it with: `"@babel/runtime-corejs2": "^7.0.0",`.

I also updated my .bablerc under plugins: 
```
[
      "@babel/plugin-transform-runtime", {
        "corejs": 2,
        "regenerator": true,
        "helpers": true
      }
]
```

`quasar build` is now working as expected.

**Comment by wooliet** [comment]
I'm using quasar cli **v0.17.19** and am running into the _"Cannot find module '@babel/runtime/core-js/get-iterator'"_ issue.  

Are there any "official" instructions or update procedures from quasar team?

**Comment by adamkpurdy** [comment]
@wooliet did you try the approach I posted? You need to update your package.json & your .bablerc in the plugins array.

**Comment by wooliet** [comment]
@adamkpurdy, the problem turned out to be one of our other dependencies. 

However, we _did_ try your steps but it did not resolve the issue.

**Comment by adamkpurdy** [comment]
@wooliet Oh interesting, just curious, but what dependency was the issue for you guys?

**Comment by wooliet** [comment]
https://github.com/GetStream/stream-js

**Comment by kyriediculous** [comment]
The error appears to be that quasar will throw this when any package being that uses babel , uses a higher version than quasar's

That's bad.
