### ISSUE TITLE
Missing dependency 'ms' for Electron builds with quasar-cli 0.16

### ISSUE THREAD

**Issue by lbssousa** [quasarframework/quasar-cli#126]
### Software version

OS: Xubuntu 18.04
Node: 8 11.2
Yarn: 1.7.0

### What did you get as the error?
After building an Electron app for my project (quasar-cli 0.16 with electron-builder bundler) and trying to run it, I've got this error message:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'ms'
    at Module._resolveFilename (module.js:543:15)
    at Function.Module._resolveFilename (/tmp/.mount_mae-0.BsxZji/app/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:473:25)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/tmp/.mount_mae-0.BsxZji/app/resources/app.asar/electron-main.js:1:6286)
    at n (/tmp/.mount_mae-0.BsxZji/app/resources/app.asar/electron-main.js:1:279)
    at Object.<anonymous> (/tmp/.mount_mae-0.BsxZji/app/resources/app.asar/electron-main.js:1:2567)
    at n (/tmp/.mount_mae-0.BsxZji/app/resources/app.asar/electron-main.js:1:279)
    at Object.<anonymous> (/tmp/.mount_mae-0.BsxZji/app/resources/app.asar/electron-main.js:1:3199)

```
I'm not sure if it's related to the fact I'm using Yarn rather than NPM to build it (my whole project uses Yarn). I can work around this problem by adding the module `ms` explicitly to my project dependencies, but I assume quasar-cli should handle it automatically, no?

**Comment by rstoenescu** [comment]
This is more likely a problem within the electron packages themselves. Quasar CLI already includes the "ms" dependency, so please refer to them about this.

If you are the one importing "ms" in the main process code, then you need to add this to your "dependencies" in the root of the project yourself. Any dependency that goes into devDependency is not included in the packaged app (to reduce size of the build, of course).
